// frontend/packages/create-ewp/templates/react/frontend/src/App.jsx
import { useState } from 'react';
import Frame from './Frame.jsx';
import colorLogo from './assets/ewp-color.svg';
import darkLogo from './assets/ewp-dark.svg';
import monoLogo from './assets/ewp-mono.svg';

export default function App() {
  const [count, setCount] = useState(0);
  const [windowStyle, setWindowStyle] = useState('macos');
  return (
    <Frame title={document.title} windowStyle={windowStyle}>
      <main className="app-view">
        <section className="welcome-card">
          <header className="welcome-header">
            <picture className="brand-mark">
              <source srcSet={monoLogo} media="(prefers-color-scheme: dark)" />
              <img src={darkLogo} alt="" width="22" height="22" />
            </picture>
            <span className="eyebrow">React · JavaScript</span>
          </header>
          <img className="hero-logo" src={colorLogo} alt="Easy Windows Pack" width="160" height="160" />
          <p className="brand-name">Easy Windows Pack</p>
          <h1>__EWP_heading__</h1>
          <p className="description">__EWP_description__</p>
          <div className="controls">
            <button className="counter" type="button" onClick={() => setCount(value => value + 1)}>__EWP_counter__: {count}</button>
          </div>
          <p className="hint">__EWP_hint__ <code>__EWP_editFile__</code> __EWP_saveHint__</p>
          <nav className="welcome-links" aria-label="__EWP_resources__">
            <a href="https://github.com/Binceenigne/easy-windows-pack" target="_blank" rel="noopener noreferrer">__EWP_source__ <span aria-hidden="true">↗</span></a>
            <a href="https://github.com/Binceenigne/easy-windows-pack/tree/main/docs" target="_blank" rel="noopener noreferrer">__EWP_docs__ <span aria-hidden="true">↗</span></a>
          </nav>
          <label className="window-style">__EWP_windowStyle__
            <select value={windowStyle} onChange={event => setWindowStyle(event.target.value)}>
              <option value="macos">macOS</option><option value="windows">Windows</option>
            </select>
          </label>
        </section>
      </main>
    </Frame>
  );
}

// frontend/packages/create-ewp/templates/vue/frontend/src/App.vue
<script setup>
import { ref } from 'vue';
import Frame from './Frame.vue';
import colorLogo from './assets/ewp-color.svg';
import darkLogo from './assets/ewp-dark.svg';
import monoLogo from './assets/ewp-mono.svg';

const count = ref(0);
const windowStyle = ref('macos');
const title = document.title;
</script>

<template>
  <Frame :title="title" :window-style="windowStyle">
    <main class="app-view">
      <section class="welcome-card">
        <header class="welcome-header">
          <picture class="brand-mark">
            <source :srcset="monoLogo" media="(prefers-color-scheme: dark)" />
            <img :src="darkLogo" alt="" width="22" height="22" />
          </picture>
          <span class="eyebrow">Vue · JavaScript</span>
        </header>
        <img class="hero-logo" :src="colorLogo" alt="Easy Windows Pack" width="160" height="160" />
        <p class="brand-name">Easy Windows Pack</p>
        <h1>__EWP_heading__</h1>
        <p class="description">__EWP_description__</p>
        <div class="controls">
          <button class="counter" type="button" @click="count++">__EWP_counter__: {{ count }}</button>
        </div>
        <p class="hint">__EWP_hint__ <code>__EWP_editFile__</code> __EWP_saveHint__</p>
        <nav class="welcome-links" aria-label="__EWP_resources__">
          <a href="https://github.com/Binceenigne/easy-windows-pack" target="_blank" rel="noopener noreferrer">__EWP_source__ <span aria-hidden="true">↗</span></a>
          <a href="https://github.com/Binceenigne/easy-windows-pack/tree/main/docs" target="_blank" rel="noopener noreferrer">__EWP_docs__ <span aria-hidden="true">↗</span></a>
        </nav>
        <label class="window-style">__EWP_windowStyle__
          <select v-model="windowStyle"><option value="macos">macOS</option><option value="windows">Windows</option></select>
        </label>
      </section>
    </main>
  </Frame>
</template>
