// packages/create-ewp/templates/vue-ts/frontend/src/Frame.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, shallowRef, watch } from 'vue';
import { mountFrame } from 'easywindowspack';
import type { MountedFrame } from 'easywindowspack';

const props = withDefaults(defineProps<{ title?: string; windowStyle?: 'macos' | 'windows' }>(), { title: 'Desktop App', windowStyle: 'macos' });
const root = ref<HTMLDivElement | null>(null);
const content = shallowRef<HTMLElement | null>(null);
let frame: MountedFrame | undefined;
onMounted(() => {
  if (!root.value) return;
  frame = mountFrame(root.value, { title: props.title, windowStyle: props.windowStyle });
  content.value = frame.content;
});
watch(() => [props.title, props.windowStyle], () => frame?.update({ title: props.title, windowStyle: props.windowStyle }));
onBeforeUnmount(() => { frame?.dispose(); });
</script>

<template>
  <div ref="root" class="desktop-frame"></div>
  <Teleport v-if="content" :to="content"><slot /></Teleport>
</template>

// packages/create-ewp/templates/react-ts/frontend/src/Frame.tsx
import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { mountFrame } from 'easywindowspack';
import type { MountedFrame } from 'easywindowspack';

type FrameProps = { title?: string; windowStyle?: 'macos' | 'windows'; children: ReactNode };

export default function Frame({ title = 'Desktop App', windowStyle = 'macos', children }: FrameProps) {
  const root = useRef<HTMLDivElement>(null);
  const frame = useRef<MountedFrame | null>(null);
  const [content, setContent] = useState<HTMLElement | null>(null);
  useEffect(() => {
    if (!root.current) return;
    const instance = mountFrame(root.current);
    frame.current = instance;
    setContent(instance.content);
    return () => { frame.current = null; instance.dispose(); };
  }, []);
  useEffect(() => { frame.current?.update({ title, windowStyle }); }, [title, windowStyle]);
  return <><div ref={root} className="desktop-frame" />{content && createPortal(children, content)}</>;
}
