// packages/create-ewp/templates/react/frontend/src/Frame.jsx
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { mountFrame } from 'easywindowspack';

export default function Frame({ title = 'Desktop App', windowStyle = 'macos', children }) {
  const root = useRef(null);
  const frame = useRef(null);
  const [content, setContent] = useState(null);
  useEffect(() => {
    const instance = mountFrame(root.current);
    frame.current = instance;
    setContent(instance.content);
    return () => { frame.current = null; instance.dispose(); };
  }, []);
  useEffect(() => { frame.current?.update({ title, windowStyle }); }, [title, windowStyle]);
  return <><div ref={root} className="desktop-frame" />{content && createPortal(children, content)}</>;
}

// packages/create-ewp/templates/vue/frontend/src/Frame.vue
<script setup>
import { onMounted, onBeforeUnmount, ref, shallowRef, watch } from 'vue';
import { mountFrame } from 'easywindowspack';

const props = defineProps({ title: { type: String, default: 'Desktop App' }, windowStyle: { type: String, default: 'macos' } });
const root = ref(null);
const content = shallowRef(null);
let frame;
onMounted(() => {
  frame = mountFrame(root.value, { title: props.title, windowStyle: props.windowStyle });
  content.value = frame.content;
});
watch(() => [props.title, props.windowStyle], () => frame?.update({ title: props.title, windowStyle: props.windowStyle }));
onBeforeUnmount(() => { frame?.dispose(); });
</script>

<template>
  <div ref="root" class="desktop-frame"></div>
  <Teleport v-if="content" :to="content"><slot /></Teleport>
</template>
